# Site settings
title: Frederik Van Geloven - UX Designer
email: fred@madebyfred.com
description: Frederik Van Geloven Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fredvg.com" # the base hostname & protocol for your site
twitter_username: frederikvg
github_username:  fredvg
linkedin_url: https://www.linkedin.com/in/fredvg/

# Build settings
markdown: kramdown
